### ISSUE TITLE
Infinite redirect loop on the wp-login page

### ISSUE THREAD

**Issue by bndn** [factmaven/disable-blogging#1] opened 2016-06-23 13:50 UTC
I just install your plugin (1.2.1) and when it’s enabled, I cannot access wp-login and wp-cron anymore. It seems that redirect_canonical() in dsbl_feeds() makes WordPress to redirect to /wp-login.php/ and /wp-cron.php/ (with a trailing slash). I use a standard configuration on nginx and PHP-FPM.

**Comment by houseraevan** [comment] 2016-07-01 01:40
Hi @sphax3d , apologies for not getting back sooner. My notification was turned off for some reason. The issue is now fixed in (v1.2.2). Please let me know if this is still an issue for you.

Thank you for using the plugin.

**Closed as completed** 2016-07-03 02:36 UTC
Labels: bug
